stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-17
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-data-export-spring:scout-latest
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-7wfkf:scout-helmcharts-mod-data-export-spring
      version: 0.1.1
      answers:
        image.repository: docker.dev.folio.org/mod-data-export-spring
        image.tag: scout-latest
        postJob.enabled: true
      targetNamespace: scout
      name: mod-data-export-spring
timeout: 60
notification: {}
