folio:
  system:
    username: data-export-system-user
  tenant:
    validation:
      enabled: true
  schedule:
    acquisition:
      poolSize: 10
      runOnlyIfModuleRegistered: true
  quartz:
    enabled: false
    schemaName: mod_data_export_spring_quartz
    changeLog: classpath:db/changelog/changelog-quartz.xml
server:
  port: 8081
logging:
  level:
    liquibase: debug
    org.folio.des.client.*: debug
spring:
  application:
    name: mod-data-export-spring
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.xml
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  datasource:
    username: ${DB_USERNAME:folio_admin}
    password: ${DB_PASSWORD:folio_admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_DATABASE:okapi_modules}
  cloud:
    openfeign:
      okhttp:
        enabled: true
  sql:
    init:
      continue-on-error: true
  jackson:
    default-property-inclusion: non_null
  quartz:
    auto-startup: ${folio.quartz.enabled}
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz:
        scheduler:
          instanceId: AUTO
        jobStore:
          driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          tablePrefix: ${folio.quartz.schemaName}.QRTZ_
          dataSource: quartz
          misfireThreshold: 10000
          isClustered: true
          clusterCheckinInterval: 15000
        dataSource:
          quartz:
            driver: org.postgresql.Driver
            provider: hikaricp
            URL: ${spring.datasource.url}
            user: ${spring.datasource.username}
            password: ${spring.datasource.password}
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health, loggers
  endpoint:
    loggers:
      enabled: true
  influx:
    metrics:
      export:
        enabled: false
feign:
  client:
    config:
      default:
        loggerLevel: basic
application:
  kafka:
    topic-configuration:
      "data-export.job.command":
        partitions: ${DATA_EXPORT_JOB_COMMAND_TOPIC_PARTITIONS:50}
    topic-pattern: ${ENV:folio}.(.*\.)?data-export.job.update
    group-id: ${ENV:folio}-mod-data-export-spring-events-group
