openapi: 3.0.0
info:
  title: Data Export Spring Jobs
  version: v1
servers:
  - url: /data-export-spring/
paths:
  /jobs:
    get:
      description: Get jobs fy filter
      operationId: getJobs
      parameters:
        - $ref: "#/components/parameters/trait_pageable_offset"
        - $ref: "#/components/parameters/trait_pageable_limit"
        - $ref: "#/components/parameters/trait_queryable_query"
      responses:
        "200":
          description: Jobs successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobCollection"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
    post:
      description: Create or update a job
      operationId: upsertJob
      responses:
        "200":
          description: Job updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        "201":
          description: Job created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        "400":
          description: Bad Request
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/job"
        required: true
  /jobs/{id}:
    get:
      description: Get a job by the job ID
      operationId: getJobById
      parameters:
        - name: id
          in: path
          required: true
          description: UUID of the job
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: Job successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        "404":
          description: Job with a given ID not found
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
components:
  schemas:
    jobStatus:
      $ref: 'schemas/jobStatus.json#/JobStatus'
    exportType:
      $ref: 'schemas/exportType.json#/ExportType'
    job:
      $ref: 'schemas/job.json#/Job'
    jobCollection:
      $ref: 'schemas/jobCollection.json#/JobCollection'
    error:
      $ref: 'schemas/common/error.json#/Error'
    UUID:
      type: string
      format: uuid
  parameters:
    trait_queryable_query:
      name: query
      in: query
      description: A query string to filter rules based on matching criteria in fields.
      schema:
        type: string
    trait_pageable_offset:
      name: offset
      in: query
      description: Skip over a number of elements by specifying an offset value for
        the query
      schema:
        default: 0
        minimum: 0
        maximum: 2147483647
        type: integer
    trait_pageable_limit:
      name: limit
      in: query
      description: Limit the number of elements returned in the response
      schema:
        default: 10
        minimum: 0
        maximum: 2147483647
        type: integer
  examples:
    error:
      value:
        $ref: 'examples/error.sample'
