ALTER TABLE job ALTER COLUMN type TYPE VARCHAR(128) USING type::TEXT;
ALTER TABLE job ALTER COLUMN status TYPE VARCHAR(128) USING status::TEXT;
ALTER TABLE job ALTER COLUMN batch_status TYPE VARCHAR(128) USING batch_status::TEXT;
ALTER TABLE job ALTER COLUMN identifier_type TYPE VARCHAR(128) USING identifier_type::TEXT;
ALTER TABLE job ALTER COLUMN entity_type TYPE VARCHAR(128) USING entity_type::TEXT;

DROP TYPE IF EXISTS batchstatus CASCADE;
DROP TYPE IF EXISTS entitytype CASCADE;
DROP TYPE IF EXISTS exporttype CASCADE;
DROP TYPE IF EXISTS identifiertype CASCADE;
DROP TYPE IF EXISTS jobstatus CASCADE;
